name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: Test
        run: >
          dotnet test
          --no-build
          -c Release
          --project src/jsConnect.Tests/jsConnect.Tests.csproj
          --results-directory ./coverage
          --coverage
          --coverage-settings src/jsConnect.Tests/CodeCoverage.config
          --coverage-output-format cobertura
          --coverage-output coverage.cobertura.xml
      - name: Check coverage report
        run: python3 .github/scripts/check-coverage.py ./coverage/coverage.cobertura.xml
      - name: Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage.cobertura.xml
          disable_search: true
          fail_ci_if_error: true
